#!/bin/bash

SCRIPT_VERSION="v1.1.1"

get_machines() {
  aws ec2 describe-instances \
    --filters "Name=tag:Name,Values=service-cluster" \
  | jq '.Reservations[].Instances[].PublicIpAddress' \
  | grep -v null \
  | xargs
}

run_on_machine() {
  local machine=$1
  local cmd=$2

  echo "running: ${machine} - ${cmd}"
  ssh \
    -o UserKnownHostsFile=/dev/null \
    -o StrictHostKeyChecking=no \
    core@$machine $cmd
}

usage(){
  echo "./run_on_major [options] <some-command>"
  echo ""
  echo "  -h, --help      print this help text"
  echo "  -v, --version   print the version"
  echo ""
}

version(){
  echo "$SCRIPT_VERSION"
}

main(){
  local cmd="$@"
  if [ "$1" == "--help" -o "$1" == "-h" ]; then
    usage
    exit 0
  fi

  if [ "$1" == "--version" -o "$1" == "-v" ]; then
    version
    exit 0
  fi

  local machines=( $(get_machines) )
  for machine in "${machines[@]}"; do
    run_on_machine "${machine}" "$cmd"
  done
}
main $@
